// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ProjectC.Migrations
{
    [DbContext(typeof(VisconContext))]
    [Migration("20231113185617_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Account", b =>
                {
                    b.Property<int>("Account_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Account_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Account_ID"));

                    b.Property<string>("Account_Email")
                        .HasColumnType("text");

                    b.Property<string>("Account_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Account_Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Account_Phone")
                        .HasColumnType("text");

                    b.Property<int?>("CustCompanyID")
                        .HasColumnType("integer");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("integer");

                    b.Property<int>("TypeAccountID")
                        .HasColumnType("integer");

                    b.HasKey("Account_ID");

                    b.HasIndex("CustCompanyID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("TypeAccountID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CustCompany", b =>
                {
                    b.Property<int>("CustCompany_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustCompany_ID"));

                    b.Property<string>("CustCompany_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustCompany_ID");

                    b.ToTable("CustCompany");
                });

            modelBuilder.Entity("Department", b =>
                {
                    b.Property<int>("Department_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Department_ID"));

                    b.Property<string>("Department_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Department_ID");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Machine", b =>
                {
                    b.Property<int>("Machine_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Machine_ID"));

                    b.Property<int?>("CustCompany_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Machine_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Machine_ID");

                    b.HasIndex("CustCompany_ID");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.Property<int>("Ticket_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Ticket_ID"));

                    b.Property<int>("AccountCustomerID")
                        .HasColumnType("integer");

                    b.Property<int>("AccountVisconID")
                        .HasColumnType("integer");

                    b.Property<int>("MachineID")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Ticket_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ticket_Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ticket_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ticket_Photo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Ticket_ID");

                    b.HasIndex("AccountCustomerID");

                    b.HasIndex("AccountVisconID");

                    b.HasIndex("MachineID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TypeAccount", b =>
                {
                    b.Property<int>("Type_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Type_ID"));

                    b.Property<string>("Type_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Type_ID");

                    b.ToTable("TypeAccounts");
                });

            modelBuilder.Entity("Account", b =>
                {
                    b.HasOne("CustCompany", "CustCompany")
                        .WithMany()
                        .HasForeignKey("CustCompanyID");

                    b.HasOne("Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID");

                    b.HasOne("TypeAccount", "TypeAccount")
                        .WithMany()
                        .HasForeignKey("TypeAccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustCompany");

                    b.Navigation("Department");

                    b.Navigation("TypeAccount");
                });

            modelBuilder.Entity("Machine", b =>
                {
                    b.HasOne("CustCompany", null)
                        .WithMany("Machines")
                        .HasForeignKey("CustCompany_ID");
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.HasOne("Account", "AccountCustomer")
                        .WithMany()
                        .HasForeignKey("AccountCustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Account", "AccountViscon")
                        .WithMany()
                        .HasForeignKey("AccountVisconID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountCustomer");

                    b.Navigation("AccountViscon");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("CustCompany", b =>
                {
                    b.Navigation("Machines");
                });
#pragma warning restore 612, 618
        }
    }
}
